---
- name: Add helm apt repository key
  ansible.builtin.apt_key:
    id: "{{ helm_apt_key_fingerprint }}"
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present

- name: Add helm apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/helm.gpg]
      https://baltocdn.com/helm/stable/debian/ all main
    filename: helm
    update_cache: yes
    state: present

- name: Install helm
  ansible.builtin.apt:
    name: helm
    state: present
